services:
    server:
        build: ./
        ports:
            - "8090:3000"
        environment:
            - SERVICE=server
            - DATABASE_URL=${DATABASE_URL}
        network_mode: host
    mpp:
        build: ./
        depends_on:
            - server
        environment:
            - SERVICE=mpp
            - MPP_TOKEN_NET=${MPP_TOKEN_NET}
            - MPP_FISHING_TOKEN=${MPP_FISHING_TOKEN}
    discord:
        build: ./
        depends_on:
            - server
        environment:
            - SERVICE=discord
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - DISCORD_FISHING_TOKEN=${DISCORD_FISHING_TOKEN}
