- id: pond
  name: Pond
  nearby: []
  hasSand: true
  objects: []
- id: lake
  name: Lake
  nearby: []
  hasSand: false
  objects: []
- id: river
  name: River
  nearby: []
  hasSand: false
  objects: []
- id: sea
  name: Sea
  nearby: []
  hasSand: true
  objects: []
