- id: default
  permissions:
    - command.general.*
    - command.fishing.*
    - command.items.*
    - command.regional.*
    - command.tree.*
    - command.pokemon.*
    - command.util.*
- id: owner
  permissions:
    - "*"
